package io.r2h.engine.core

enum class TaskType {
    CHAT,
    TEXT_GENERATION,
    SUMMARIZATION,
    REWRITING,
    EXTRACTION,
    QUESTION_ANSWERING,
    IMAGE_UNDERSTANDING,
    IMAGE_TEXT_MULTIMODAL,
    IMAGE_GENERATION,
    VIDEO_FULL_ANALYSIS,
    EMBEDDING,
    RERANKING,
    CLASSIFICATION,
    OBJECT_DETECTION,
    SEGMENTATION,
    OCR,
    SPEECH_TO_TEXT,
    TEXT_TO_SPEECH,
    AUDIO_ANALYSIS,
    AUDIO_TAGGING,
}
